CREATE TABLE IF NOT EXISTS article_reaction (
    article TEXT NOT NULL,
    kind TEXT NOT NULL,
    deletion_key TEXT NOT NULL UNIQUE,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
